version: "2.3.3" 
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: WordPress_DB
      MYSQL_USER: WordPressUser
      MYSQL_PASSWORD: P@ssw0rd
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "9090:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: WordPressUser
      WORDPRESS_DB_PASSWORD: P@ssw0rd
      WORDPRESS_DB_NAME: WordPress_DB
    volumes:
      ["./:/var/www/html"]
volumes:
  mysql: {}
